name: Create Pipeline

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment name"
        required: true
        default: "dev"
        options:
          - "dev"
          - "prod"
      name:
        description: "Pipeline name. 'all' to delete all pipelines"
        required: true
        default: "all"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Replace token in config
        run: |
          for file in "pipeline/*"; do
              sed -i "s/{{ENV}}/${{ vars.ENV }}/g" $file
              sed -i "s/{{PROJECT}}/${{ vars.PROJECT }}/g" $file
          done

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Azure create pipeline
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            if [ "${{ inputs.name }}" = "all" ]; then
                ls -p pipeline | grep -v / | while read -r file; do
                    file_name="${file%.*}"
                    az datafactory pipeline create --factory-name "${{ vars.ENV }}-sandstock-adf" --pipeline @pipeline/$file --name $file_name --resource-group "${{ vars.ENV }}-sandstock-rg"
                done
            else
                az datafactory pipeline create --factory-name "${{ vars.ENV }}-sandstock-adf" --pipeline @pipeline/"${{ inputs.name }}.json" --name ${{ inputs.name }} --resource-group "${{ vars.ENV }}-sandstock-rg"
            fi