name: Delete Pipeline

on:
  workflow_dispatch:
    inputs:
      env:
        type: environment
        description: "Select the environment"
      name:
        description: "Pipeline name. 'all' to delete all pipelines"
        required: true
        default: "all"

jobs:
  delete-pipeline:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Delete ${{ inputs.name }} pipeline
      run: |
        if [ "${{ inputs.name }}" = "all" ]; then
          pipelines=$(az datafactory pipeline list --factory-name "${{ vars.ENV }}-sandstock-adf" --resource-group "${{ vars.ENV }}-sandstock-rg" --query "[].name" --output tsv)
        
          for pipeline in $pipelines; do
             az datafactory pipeline delete --factory-name "${{ vars.ENV }}-sandstock-adf" --resource-group "${{ vars.ENV }}-sandstock-rg" --name $pipeline --yes
          done
        else
          az datafactory pipeline delete --factory-name "${{ vars.ENV }}-sandstock-adf" --resource-group "${{ vars.ENV }}-sandstock-rg" --name ${{ inputs.name }} --yes
        fi