name: Create Trigger

on:
  workflow_dispatch:
    inputs:
      env:
        type: environment
        description: "Select the environment"
      name:
        description: "Trigger name. 'all' to create all triggers"
        required: true
        default: "all"

jobs:
  create-trigger:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Replace token in config
        run: |
          for file in "trigger/*"; do
              sed -i "s/{{ENV}}/${{ vars.ENV }}/g" $file
              sed -i "s/{{PROJECT}}/${{ vars.PROJECT }}/g" $file
          done

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Create ${{ inputs.name }} trigger
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            if [ "${{ inputs.name }}" = "all" ]; then
                ls -p trigger | grep -v / | while read -r file; do
                    file_name="${file%.*}"
                    json=$(jq ".properties" "trigger/$file")
                    az datafactory trigger create --factory-name "${{ vars.ENV }}-sandstock-adf" --properties "$json" --name $file_name --resource-group "${{ vars.ENV }}-sandstock-rg"
                done
            else
                json=$(jq ".properties" "trigger/${{ inputs.name }}.json")
                az datafactory trigger create --factory-name "${{ vars.ENV }}-sandstock-adf" --properties "$json" --name ${{ inputs.name }} --resource-group "${{ vars.ENV }}-sandstock-rg"
            fi